#define FITSVERSION "3.0.1"
#define FITSVERSION_NUM 3.0.1
#define FITSMAJORVERSION "3"
#define FITSMAJORVERSION_NUM 3
#define FITSMINORVERSION "0"
#define FITSMINORVERSION_NUM 3
#define FITSCOPYRIGHTYEAR 2004-2011
#define FITSBUNDLEIDENTIFIER "org.spacetelescope.fits_liberator"
