//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FitsLiberator.rc
//
#define IDI_FITSLIBERATOR               1
#define MANIFEST_RESOURCE_ID            2
#define IDS_STRING3                     3
#define IDB_USEBLACKLEVEL               188
#define IDB_USEWHITELEVEL               189
#define IDD_TAXONOMYEDITOR              200
#define IDB_CHECKBOX_CHECKED            203
#define IDB_CHECKBOX_UNCHECKED          204
#define IDB_CHECKBOX_EMPTY              205
#define IDM_STRETCH_MENU                206
#define IDD_OPTIONS                     207
#define IDB_THROBBER                    209
#define IDB_ABOUT                       1000
#define IDD_ABOUT                       1000
#define IDC_VERSION                     1002
#define IDC_TAXONOMY_CATEGORIES         1002
#define IDC_PROGRESS                    1089
#define IDC_PREVIEW_ZOOM                1090
#define IDC_GLOBAL_SCALED               1109
#define IDC_STATISTICS_MODE             1112
#define IDC_GLOBAL_STRETCHED            1113
#define IDC_PICKER_MODE                 1114
#define IDC_SCALE                       1123
#define IDC_TAXONOMY_SCALE              1123
#define IDC_BUTTON1                     1124
#define IDC_OPTIONS_STATS               1124
#define IDC_COMBO1                      1125
#define IDC_OPTIONS_DEFAULTS            1125
#define IDC_TAB1                        1126
#define IDC_OPTIONS_CLEARHISTORY_XP     1126
#define IDC_DEFAULT_STRETCH             1127
#define IDC_COMMAND1                    1130
#define IDC_OPTIONS_CLEARHISTORY        1130
#define IDC_COMBOBOXEX1                 1137
#define IDC_COMBO2                      1138
#define IDC_OPTIONS_GUESS               1138
#define IDC_SLIDER1                     1139
#define IDC_SLIDER2                     1140
#define IDC_OPTIONS_SCALEDPEAK          1141
#define IDC_OPTIONS_STRETCH             1142
#define IDC_OPTIONS_BLACKLEVEL          1143
#define IDC_OPTIONS_SCALEDPEAK3         1144
#define IDC_OPTIONS_WHITELEVEL          1144
#define IDC_HELPGUIDE_TEXT              1144
#define IDC_OPTIONS_SHOWGRID            1145
#define IDC_OPTIONS_SHOWBACKGROUND      1146
#define IDC_OPTIONS_SHOWSCALEDPEAK      1147
#define IDC_OPTIONS_SHOWPEAK            1147
#define IDC_OPTIONS_MARGIN              1148
#define IDC_OPTIONS_SHOWZERO            1150
#define IDC_OPTIONS_SHOWMEAN            1151
#define IDC_OPTIONS_SHOWSTRETCHEDMEAN   1152
#define IDC_OPTIONS_SHOWSCALEDMEAN      1153
#define IDC_OPTIONS_SHOWMEDIAN          1154
#define IDC_WARNING_NETWORK             1156
#define IDC_OPTIONS_APPLYSTRETCHDIRECTLY 1157
#define IDC_OPTIONS_SHOWSTRETCHEDMEDIAN 1159
#define IDC_OPTIONS_SHOWZERO7           1160
#define IDC_OPTIONS_SHOWSCALEDMEDIAN    1160
#define IDB_PREVIEW_LOGO                2000
#define IDD_MAIN                        2000
#define IDC_PAGES                       2001
#define IDC_OK                          2002
#define IDC_STRETCH_AUTOSCALE           2003
#define IDC_RESET                       2004
#define IDC_STRETCH_APPLYSTRETCH        2005
#define IDD_PREVIEW                     3000
#define IDC_PLANE_FIRST                 3100
#define IDC_PLANE_SELECTOR              3101
#define IDC_PLANE_WIDTH                 3102
#define IDC_PLANE_HEIGHT                3103
#define IDC_PLANE_CHANNEL_8             3104
#define IDC_PLANE_CHANNEL_16            3105
#define IDC_PLANE_CHANNEL_32            3106
#define IDC_PLANE_UNDEFINED_BLACK       3107
#define IDC_PLANE_UNDEFINED_TRANSPARENT 3108
#define IDC_PLANE_FLIP                  3109
#define IDC_PLANE_LAST                  3110
#define IDC_GLOBAL_FIRST                3200
#define IDC_GLOBAL_PREVIEW              3201
#define IDC_GLOBAL_UNDEFINED            3202
#define IDC_GLOBAL_WHITE                3203
#define IDC_GLOBAL_BLACK                3204
#define IDC_GLOBAL_FREEZE               3205
#define IDC_GLOBAL_LAST                 3206
#define IDS_CATEGORYBUTTON_TEXT         3206
#define IDS_TAXONOMYEDITOR              3206
#define IDB_BRUSH_TRANSPARENT           3300
#define IDC_PREVIEW_FIRST               3300
#define IDM_PREVIEW_MENU                3300
#define IDC_PREVIEW                     3301
#define IDC_PREVIEW_FIT                 3302
#define IDC_PREVIEW_ACTUAL              3303
#define IDC_PREVIEW_ZOOMIN              3304
#define IDC_CURSOR_ZOOMIN               3304
#define IDC_PREVIEW_ZOOMOUT             3305
#define IDC_CURSOR_ZOOMOUT              3305
#define IDC_PREVIEW_CENTER              3306
#define IDC_CURSOR_ZOOMIN2              3306
#define IDC_CURSOR_ZOOMLIMIT            3306
#define IDC_PREVIEW_ZOOMLIST            3307
#define IDC_CURSOR_ZOOMIN1              3307
#define IDC_CURSOR_HAND                 3307
#define IDC_PREVIEW_PROGRESS            3308
#define IDC_PREVIEW_ZOOM0               3310
#define IDC_PREVIEW_LAST                3350
#define IDI_HISTOGRAM_SLIDER_BLACK      3400
#define IDC_HISTOGRAM_FIRST             3400
#define IDM_HISTOGRAM_MENU              3400
#define IDI_HISTOGRAM_SLIDER_DISABLED   3401
#define IDC_HISTOGRAM_CONTROL           3401
#define IDI_HISTOGRAM_SLIDER_WHITE      3402
#define IDC_HISTOGRAM_SLIDER            3402
#define IDC_HISTOGRAM_MIN               3403
#define IDC_HISTOGRAM_MAX               3404
#define IDC_HISTOGRAM_WHITE             3405
#define IDC_HISTOGRAM_BLACK             3406
#define IDC_HISTOGRAM_BLACKSPIN         3407
#define IDC_HISTOGRAM_WHITESPIN         3408
#define IDC_HISTOGRAM_SHOWALL           3409
#define IDC_HISTOGRAM_ZOOMIN            3410
#define IDC_HISTOGRAM_ZOOMOUT           3411
#define IDC_HISTOGRAM_LAST              3412
#define IDC_STRETCH_FIRST               3500
#define IDC_STRETCH_FUNCTION            3501
#define IDC_STRETCH_BACKGROUND          3502
#define IDC_STRETCH_RESCALE             3503
#define IDC_STRETCH_MAXRANGE            3504
#define IDC_STRETCH_RESET               3505
#define IDC_STRETCH_FUNCTION2           3505
#define IDC_STRETCH_AUTOBACKGROUND      3506
#define IDC_STRETCH_AUTOPEAK            3507
#define IDC_OPTIONS                     3508
#define IDC_STRETCH_LINEAR              3510
#define IDC_STRETCH_ARCSINH             3512
#define IDC_STRETCH_LOG                 3513
#define IDC_STRETCH_SQRT                3515
#define IDC_STRETCH_CUBEROOT            3516
#define IDC_STRETCH_FOURTHROOT          3517
#define IDC_STRETCH_FIFTHROOT           3518
#define IDC_STRETCH_POW15               3520
#define IDC_STRETCH_POW2                3521
#define IDC_STRETCH_POW3                3522
#define IDC_STRETCH_POW4                3523
#define IDC_STRETCH_POW5                3524
#define IDC_STRETCH_EXP                 3525
#define IDC_STRETCH_ARCSINH_ARCSINH     3527
#define IDC_STRETCH_ARCSINH_SQRT        3528
#define IDC_STRETCH_LOG_LOG             3529
#define IDC_STRETCH_LOG_SQRT            3530
#define IDC_STRETCH_LAST                3531
#define IDC_IO_SAVEFILE                 3532
#define IDC_IO_OPENNEW                  3533
#define IDC_SHOWABOUT                   3534
#define IDC_IO_SAVEFILE2                3535
#define IDC_IO_EDIT                     3535
#define IDB_TOOL_HOT                    3600
#define IDC_TOOL_FIRST                  3600
#define IDB_TOOL_NORMAL                 3601
#define IDC_TOOL_MOVE                   3601
#define IDC_TOOL_ZOOM                   3602
#define IDC_TOOL_BACKGROUND             3603
#define IDC_TOOL_PEAK                   3604
#define IDC_TOOL_BLACK                  3605
#define IDC_TOOL_WHITE                  3606
#define IDC_TOOL_LAST                   3607
#define IDC_STATISTICS_FIRST            3700
#define IDC_STATISTICS_STDDEV_REAL      3701
#define IDC_STATISTICS_STDDEV_STRETCHED 3702
#define IDC_STATISTICS_MEDIAN_REAL      3703
#define IDC_STATISTICS_MEDIAN_STRETCHED 3704
#define IDC_STATISTICS_MEAN_STRETCHED   3705
#define IDC_STATISTICS_MEAN_REAL        3706
#define IDC_STATISTICS_MAX_REAL         3707
#define IDC_STATISTICS_MIN_REAL         3708
#define IDC_STATISTICS_MIN_STRETCHED    3709
#define IDC_STATISTICS_MAX_STRETCHED    3710
#define IDC_STATISTICS_LAST             3711
#define IDC_PICKER_FIRST                3800
#define IDC_PICKER_REAL                 3801
#define IDC_PICKER_STRETCHED            3802
#define IDC_PICKER_Y                    3803
#define IDC_PICKER_X                    3804
#define IDC_PICKER_RA                   3805
#define IDC_PICKER_DEC                  3806
#define IDC_PICKER_LAST                 3807
#define IDD_REPOSITORY                  4000
#define IDC_REPOSITORY                  4001
#define IDC_INCORRECT_INPUT_TITLE       4001
#define IDC_INCORRECT_INPUT_MESSAGE     4002
#define ID_DUMMY_LINEAR                 4042
#define ID_DUMMY_ARCSINH                4043
#define ID_DUMMY_LOG                    4044
#define ID_DUMMY_X                      4045
#define ID_DUMMY_X4046                  4046
#define ID_DUMMY_X4047                  4047
#define ID_DUMMY_X4048                  4048
#define ID_DUMMY_ARCSINH4049            4049
#define ID_DUMMY_ARCSINH4050            4050
#define ID_DUMMY_LOG4051                4051
#define ID_DUMMY_LOG4052                4052
#define ID_STRETCH_X                    4053
#define ID_Menu                         4054
#define ID_STRETCH_X4055                4055
#define ID_STRETCH_X4056                4056
#define ID_STRETCH_X4057                4057
#define ID_STRETCH_EXP                  4058
#define ID_STRETCH_X4059                4059
#define ID_IMAGE_OPENFILE               4071
#define ID_IMAGE_SAVEFILE               4072
#define ID_IMAGE_SAVEEDIT               4073
#define IDD_HEADER                      5000
#define IDC_HEADER                      5001
#define IDS_CATEGORY_FILE               6000
#define IDC_MARKER_RED                  6000
#define IDS_CATEGORY_ID                 6001
#define IDS_CATEGORY_PROCESSING         6002
#define IDS_CATEGORY_INFO               6003
#define IDC_MARKER_GREEN                6003
#define IDS_CATEGORY_ASTRO              6004
#define IDC_MARKER_MAGENTA              6004
#define IDC_MARKER_BLUE                 6006
#define IDC_MARKER_PURPLE               6007
#define IDS_AUTHOR                      6100
#define IDS_NAME                        6100
#define IDS_VALUE                       6101
#define IDS_ID                          6102
#define IDS_HEADER_HEADING              6103
#define IDS_STRETCH_LINEAR              6200
#define IDS_STRETCH_ASINH               6202
#define IDS_STRETCH_LOG                 6203
#define IDS_STRETCH_SQRT                6205
#define IDS_STRETCH_CUBEROOT            6206
#define IDS_STRETCH_ROOT4               6207
#define IDS_STRETCH_ROOT5               6208
#define IDS_STRETCH_15                  6210
#define IDS_STRETCH_POW2                6211
#define IDS_STRETCH_POW3                6212
#define IDS_STRETCH_POW4                6213
#define IDS_STRETCH_NOSTRETCH           6214
#define IDS_STRETCH_EXP                 6215
#define IDS_STRETCH_ASINHASINH          6217
#define IDS_STRETCH_ASINHSQRT           6218
#define IDS_STRETCH_LOGLOG              6219
#define IDS_STRETCH_LOGSQRT             6220
#define IDS_STRETCH_POW5                6221
#define IDS_VERSION                     6300
#define IDS_TITLE_BAR_TITLE             6400
#define IDS_INVALIDBITDEPTH             7000
#define IDS_FAILEDTOCREATEWINDOW        7001
#define IDS_INVALID_HEADER              7100
#define IDS_INVALID_INTEGER             7101
#define IDS_INVALID_ELEMENTCOUNT        7101
#define IDS_INVALID_REAL                7102
#define IDS_INVALID_POINT               7103
#define IDS_INVALID_DATE                7103
#define IDS_INVALID_DATETIME            7104
#define IDS_INVALID_TIME                7105
#define IDS_INVALID_URLID               7106
#define IDS_INVALID_URL                 7107
#define IDS_INVALID_URLRESOURCE         7107
#define IDS_INVALID_IVOID               7108
#define IDS_INVALID_IVOIDENTIFIER       7109
#define IDS_INVALID_URI                 7110
#define IDS_INVALID_IVORESOURCE         7110
#define IDS_STATS_PROGRESS_REAL         7201
#define IDS_STATS_RANGE_PROGRESS_REAL   7202
#define IDS_STATS_PROGRESS_STRETCH      7203
#define IDS_STATS_RANGE_PROGRESS_STRETCH 7204
#define IDS_IMAGE_LOAD_CHUNK            7205
#define IDS_STRETCH_STRETCHING          7206
#define IDD_PROGRESS                    8000
#define IDD_HELPGUIDE                   8001
#define IDC_STATIC                      -1
#define IDC_DUMMY                       -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         4074
#define _APS_NEXT_CONTROL_VALUE         1157
#define _APS_NEXT_SYMED_VALUE           123
#endif
#endif
